-- DODAWANIE WPISÓW
-- INSERT INTO public."Customer" ("ID", "FIRST_NAME") VALUES (3, 'Jan');

-- ODCZYTYWANIE WPISÓW
-- SELECT "FIRST_NAME" FROM public."Customer" ORDER BY "ID" ASC;
-- SELECT "FIRST_NAME" FROM public."Customer" ORDER BY "ID" DESC;
-- SELECT * FROM public."Customer" WHERE "FIRST_NAME" LIKE 'A%' ORDER BY "FIRST_NAME" DESC;

-- AKTULIZACJA WPISÓW (WHERE!)
-- UPDATE "Customer" SET "DATE_OF_BIRTH" = '1960-01-01' WHERE "ID" = 2;

-- USUWANIE WPISÓW (WHERE!)
DELETE FROM "Customer" WHERE "ID" > 2;

-- CRUD